version: '3'

services:
  weatherapp:
    container_name:  weatherapp
    restart: always
    build: ./weatherapp
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:app
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      -  weatherapp
